[package]
name = "kino"
version = "0.1.0"
edition = "2024"

[dependencies]
alphanumeric-sort = "1.5"

bytes = "1"

chrono = { version = "0.4", features = ["std", "now"]}

glib = "0.20" # gobject traits and error type
gstreamer = "0.23"
gstreamer-app = "0.23" # appsink
gstreamer-base = "0.23" # basesrc

iced = { git = "https://github.com/iced-rs/iced", rev = "c67f523", features = ["image", "svg", "hot", "tokio", "advanced", "wgpu", "markdown"] }
iced_video_player = { git = "https://github.com/EmmanuelDodoo/iced_video_player" }
# iced_video_player = { path = "../ivp_fork" }
image = "0.25"

rand = "0.8"
rfd = "0.16"
rusqlite = {version = "0.37", features = ["bundled", "uuid", "chrono"]}

tokio = "1.47"

url = "2"
uuid = {version = "1.18", features = ["v7", "std"]}
