[video]
thumbnail_interval = 10
volume = 1.0
speed = 1.5000000000000004
volume_change_amt = 0.05
seek_change_amt = 5.0
seek_shift_change_amt = 10.0
speed_change_amt = 0.1
show_subtitles = true
muted = false
auto_start = true
auto_next = true
completion_point = 0.95
completion_watch_time = 0.75
comment_span = 90

[video.subtitles]
size = 20
color = "#ff8243"
font = "Roboto"
background_color = "#000000af"

[video.filters]
brightness = 0.0
contrast = 1.0
hue = 0.0
saturation = 1.0
gamma = 1.0

[general]
layout = "Grid"
recents_limit = 5
search_limit = 5
scan_discoverer = true
auth_token = ""
movie_depth = 2
restore_deleted = true
preferred_subtitle_codec = "en"
preferred_audio_codec = "en"
tmdb_rating = true
default_source = "tmdb"
show_dirs = false

[general.refresh_interval]
secs = 600
nanos = 0

[general.fetching_interval]
secs = 60
nanos = 0
